# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        sound_cover:
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 300, 300 ], mode: outbound }
                    
                
        instrument_swiper_crop:
            quality: 75
                
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                crop: 
                    size: [ 132, 264 ]
                    start: [ 0, 0 ]
                    
        instrument_swiper_thumb:

            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
#                thumbnail: { size: [ 132, 264 ], mode: outbound }   
                relative_resize:
                    
                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 264
