twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        mailer_from: '%mailer_from%'
        instrument_dir: '%instrument_dir%'
        sound_dir: '%sound_dir%'
        company_dir: '%company_dir%'

when@test:
    twig:
        strict_variables: true
