vich_uploader:
    db_driver: orm

    mappings:
        sounds:
            uri_prefix: '%sound_dir%'
            upload_destination: '%kernel.project_dir%/public/%sound_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
